telegram_token: <<value>> # Telegram token id
chatbase_token: <value> # Chatbase token for store statistic
pause_mailing: 10 # Delay between messages in mailing
admin_chat_id: <value> # Chat id with you and your bot

# Try to store users on mysql database
# Not working
mysql_host: <value>
mysql_port: <value>
mysql_user: <value>
mysql_pass: <value>
mysql_dbname: <value>
mysql_table: <value>

use_ssh: <value>
ssh_host: <value>
ssh_user: <value>
ssh_pass: <value>
forward_port: <value>